services:
  dicedb:
    image: dicedb/dicedb:latest
    ports:
      - "7379:7379"
    healthcheck:
     test: ["CMD", "PING"]
     interval: 10s
     timeout: 3s
     retries: 3
    networks:
     - dice-network

  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - dicedb
    environment:
      - DICEDB_ADDR=localhost:7379
      - DICEDB_USERNAME=${DICEDB_USERNAME}
      - DICEDB_PASSWORD=${DICEDB_PASSWORD}
    networks:
     - dice-network
    
networks:
 dice-network:
  driver: bridge

